### ISSUE TITLE
Where is the "Add a comment" in your blog?

### ISSUE THREAD

**Issue by doggy8088** [JuergenGutsch/blog#130]
I saw [this article](https://asp.net-hacker.rocks/2018/07/09/aspnetcore-ssl.html) about "If you found any error on this post, feel free to tell me: Add a comment below, file an issue on GitHub or edit this page on GitHub and send me an PullRequest." in your blog.  But I can't see any GitHub comment block.  Where is it?

**Comment by JuergenGutsch** [comment]
Hi @doggy8088 
I disabled all third party JavaScript add-in, like google Analytics, google Adsense, as well as the comments until you accept the privacy policy. This is I thing I need to do because of GDPR EU regulations.
If you don't want to accept the privacy policy, you are able to find the relating comment thread here in the issues. Find the issue related to the post and add a comment to the issue. It will appear on the blog, to all users who accept the policy.

**Comment by doggy8088** [comment]
@JuergenGutsch Can you add your blog link into this repo?

![image](https://user-images.githubusercontent.com/88981/51699465-c6b49100-2047-11e9-88be-db392c8c575b.png)

**Comment by JuergenGutsch** [comment]
@doggy8088 Makes sense :-) Thanks for the hint. It's done.
